apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: z-mart
  name: z-mart
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: z-mart
  name: z-mart
  namespace: z-mart
spec:
  type: ClusterIP
  selector:
    app: z-mart
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: z-mart
  namespace: z-mart
  labels:
    app: z-mart
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: z-mart
  template:
    metadata:
      labels:
        app: z-mart
    spec:
      containers:
        - name: z-mart
          image: ghcr.io/z-mart-dev/z-mart:latest
          imagePullPolicy: Always
          stdin: true
          tty: true
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
          resources: {}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: z-mart
  namespace: z-mart
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
    - hosts:
        - docs.z-mart.dev
      secretName: z-mart-tls
  rules:
    - host: docs.z-mart.dev
      http:
        paths:
          - path: /
            backend:
              serviceName: z-mart
              servicePort: 80
